apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - image:  aluracursos/portal-noticias:1
      name:  portal-noticias-container
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap