apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: lsales
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80 
    name: webserver
  dnsPolicy: ClusterFirst
  restartPolicy: Always
