apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
  namespace: giropops
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    name: webserver
  dnsPolicy: ClusterFirst
  restartPolicy: Always
