apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap
  namespace: lsales
spec:
  containers:
  - image: busybox
    name: busy-configmap
    command:
      - sleep
      - "3600"
    env:
    - name: frutas
      valueFrom:
        configMapKeyRef:
          name: cores-fruta
          key: predileta
    envFrom:
    - configMapRef:
        name: cores-fruta
