apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap-file
  namespace: lsales
spec:
  containers:
  - image: busybox
    name: busy-configmap
    command:
      - sleep
      - '3500'
    volumeMounts:
    - name: meu-configmap-vol
      mountPath: /etc/fruta
  volumes:
  - name: meu-configmap-vol
    configMap:
      name: cores-fruta
