apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: lsales
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /lsales
      name: lsales-dir
  volumes:
  - name: lsales-dir
    emptyDir: {}
