apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lsales-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lsales-cronjob
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Bem vindo ao Descomplicando Kubernetes - LinuxTips VAIII; sleep 30
          restartPolicy: OnFailure
