apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-pv
spec:
  capacity:
    storage: 1Gi
  acessModes:
  - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain
  nfs:
    # somente ilustrativo
    path: /opt/dados
    server: 127.0.0.1
    readOnly: false
