apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-canary-app-v1
  labels:
    app: ms-canary-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-canary-app
  template:
    metadata:
      labels:
        app: ms-canary-app
    spec:
      containers:
      - name: ms-canary-app-v1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
