apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-canary-app-v2
  labels:
    app: ms-canary-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-canary-app
  template:
    metadata:
      labels:
        app: ms-canary-app
    spec:
      containers:
      - name: ms-canary-app-v2
        image: nickolback/ms-canary:v2
        ports:
        - containerPort: 80
